GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('mixer', 'simple', 0, GTValues.ULV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType(GTRecipeTypes.MIXER_RECIPES, true, true)
        .workableTieredHullRenderer('gtceu:block/machines/mixer')
    event.create('autoclave', 'simple', 0, GTValues.ULV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType(GTRecipeTypes.AUTOCLAVE_RECIPES, true, true)
        .workableTieredHullRenderer('gtceu:block/machines/autoclave')
    event.create('assembler', 'simple', 0, GTValues.ULV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType(GTRecipeTypes.ASSEMBLER_RECIPES, true, true)
        .workableTieredHullRenderer('gtceu:block/machines/assembler')
    event.create('circuit_assembler', 'simple', 0, GTValues.ULV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType(GTRecipeTypes.CIRCUIT_ASSEMBLER_RECIPES, true, true)
        .workableTieredHullRenderer('gtceu:block/machines/circuit_assembler')
    event.create('fermenter', 'simple', 0, GTValues.ULV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType(GTRecipeTypes.FERMENTING_RECIPES, true, true)
        .workableTieredHullRenderer('gtceu:block/machines/fermenter')
    event.create('brewery', 'simple', 0, GTValues.ULV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType(GTRecipeTypes.BREWING_RECIPES, true, true)
        .workableTieredHullRenderer('gtceu:block/machines/brewery')
    event.create('distillery', 'simple', 0, GTValues.ULV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType(GTRecipeTypes.DISTILLERY_RECIPES, true, true)
        .workableTieredHullRenderer('gtceu:block/machines/distillery')
    event.create('forming_press', 'simple', 0, GTValues.ULV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType(GTRecipeTypes.FORMING_PRESS_RECIPES, true, true)
        .workableTieredHullRenderer('gtceu:block/machines/forming_press')
    event.create('scanner', 'simple', 0, GTValues.ULV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType(GTRecipeTypes.SCANNER_RECIPES, true, true)
        .workableTieredHullRenderer('gtceu:block/machines/scanner')
    event.create('canner', 'simple', 0, GTValues.ULV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType(GTRecipeTypes.CANNER_RECIPES, true, true)
        .workableTieredHullRenderer('gtceu:block/machines/canner')
    event.create('thermal_centrifuge', 'simple', 0, GTValues.ULV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType(GTRecipeTypes.THERMAL_CENTRIFUGE_RECIPES, true, true)
        .workableTieredHullRenderer('gtceu:block/machines/thermal_centrifuge')
    event.create('centrifuge', 'simple', 0, GTValues.ULV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType(GTRecipeTypes.CENTRIFUGE_RECIPES, true, true)
        .workableTieredHullRenderer('gtceu:block/machines/thermal_centrifuge')
    event.create('ore_washer', 'simple', 0, GTValues.ULV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType(GTRecipeTypes.ORE_WASHER_RECIPES, true, true)
        .workableTieredHullRenderer('gtceu:block/machines/ore_washer')
    event.create('chemical_reactor', 'simple', 0, GTValues.ULV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType(GTRecipeTypes.CHEMICAL_RECIPES, true, true)
        .workableTieredHullRenderer('gtceu:block/machines/chemical_reactor')
    event.create('wiremill', 'simple', 0, GTValues.ULV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType(GTRecipeTypes.WIREMILL_RECIPES, true, true)
        .workableTieredHullRenderer('gtceu:block/machines/wiremill')
    event.create('electrolyzer', 'simple', 0, GTValues.ULV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType(GTRecipeTypes.ELECTROLYZER_RECIPES, true, true)
        .workableTieredHullRenderer('gtceu:block/machines/electrolyzer')
    event.create('chemical_bath', 'simple', 0, GTValues.ULV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType(GTRecipeTypes.CHEMICAL_BATH_RECIPES, true, true)
        .workableTieredHullRenderer('gtceu:block/machines/chemical_bath')
    event.create('bender', 'simple', 0, GTValues.ULV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType(GTRecipeTypes.BENDER_RECIPES, true, true)
        .workableTieredHullRenderer('gtceu:block/machines/bender')
    event.create('lathe', 'simple', 0, GTValues.ULV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType(GTRecipeTypes.LATHE_RECIPES, true, true)
        .workableTieredHullRenderer('gtceu:block/machines/lathe')
    event.create('extruder', 'simple', 0, GTValues.ULV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType(GTRecipeTypes.EXTRUDER_RECIPES, true, true)
        .workableTieredHullRenderer('gtceu:block/machines/extruder')
})

