
#Make sure config changes are duplicated on both Clients and the Server when running a dedicated Server,
# as the config isnt synced between Clients and Server.
#General Settings
[general]
	#If audio should be enabled or not.
	audio_enabled = true

	#Wires
	[general.wires]
		#If the base mod connectors should be registered
		use_base_connectors = true
		#If the preset GT connectors should be registered
		use_gt_connectors = true
		#If the preset CCA connectors should be registered
		use_cca_connectors = true
		#If your custom connectors should be registered
		use_custom_connectors = true
		#Huge Connector max wire length in blocks.
		#Range: 0 ~ 256
		huge_connector_wire_length = 64
		#Ignore checking if block face can support connector.
		connector_ignore_face_check = true
		#Allows blocks attached to a connector to freely pass energy to and from the connector network.
		connector_allow_passive_io = true

